#
# @see https://symfony.com/doc/current/reference/configuration/framework.html
#
framework:
    #
    # This is a string that should be unique to your application and it's commonly
    # used to add more entropy to security related operations. Its value should be
    # a series of characters, numbers and symbols chosen randomly and the
    # recommended length is around 32 characters.
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#secret
    #
    secret: '%env(APP_SECRET)%'

    #
    # This option can be used to disable CSRF protection on all forms. But you can
    # also disable CSRF protection on individual forms.
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#csrf-protection
    #
    csrf_protection: false

    #
    # This determines whether the _method request parameter is used as the
    # intended HTTP method on POST requests. If enabled, the
    # "Request::enableHttpMethodParameterOverride()" method gets called
    # automatically.
    #
    # It becomes the service container parameter named kernel.http_method_override.
    #
    # The default value is:
    #
    # - true: if you have an existing application that you've upgraded from an
    #         older Symfony version without resyncing the Symfony Flex recipes;
    #
    # - false: if you've created a new Symfony application or updated the Symfony
    #          Flex recipes. This is also the default value starting from
    #          Symfony 7.0.
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#http-method-override
    #
    http_method_override: false

    #
    # Symfony applications generate by default the translation files for
    # validation and security messages in all locales. If your application
    # only uses some locales, use this option to restrict the files generated by
    # Symfony and improve performance a bit.
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#enabled-locales
    #
    enabled_locales: [ 'en' ]

    #
    # Disable Doctrine annotations reader for speedup routing/validation/etc.
    # Note: Please use attributes instead
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#annotations
    #
    annotations: false

    #
    # Enables session support. Note that the session will ONLY be started if you
    # read or write from it.
    # Remove or comment this section to explicitly disable session support.
    #
    # @see https://symfony.com/doc/current/reference/configuration/framework.html#session
    #
    # session:
    #   handler_id: null
    #   cookie_secure: auto
    #   cookie_samesite: lax
    #   storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

when@test:
    framework:
        test: true
