version: '3.4'

services:
  nginx:
    image: nginx:alpine
    container_name: railt-nginx
    working_dir: /home/railt/railt.org
    volumes:
      - .:/home/railt/railt.org
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx:/var/log/nginx/
    ports:
      - "8080:80"

  php:
    build: docker/php
    container_name: railt-php
    working_dir: /home/railt/railt.org
    volumes:
      - .:/home/railt/railt.org
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
