version: "2"

services:
    php:
        image: "railt_org"
        container_name: "railt_org"
        command: "/laravel.sh"
        build:
            context: ./docker/php
            args:
                - ENABLE_XDEBUG=true
                - ENABLE_EV=true
                - ENABLE_PCNTL=true
                - INSTALL_OPCACHE=true
                - INSTALL_INTL=true
                - INSTALL_IMAGEMAGICK=true
        volumes:
            - "./:/var/www/railt.org"
            - "./docker/.mount/profiler:/var/log/profiler"
        links:
            - mysql
            - redis
        depends_on:
            - redis
            - mysql

    nginx:
        container_name: "railt_org_nginx"
        build:
            context: ./docker/nginx
            args:
                - PHP_UPSTREAM=php
        volumes_from: [php]
        volumes:
            - ./docker/nginx/sites-available/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php

    mysql:
        container_name: "railt_org_database"
        build:
            context: ./docker/mysql
            args:
                - MYSQL_VERSION=5.7
        environment:
            - MYSQL_DATABASE=railt
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - TZ=UTC
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - "3308:3306"

    redis:
        container_name: "railt_org_redis"
        build: ./docker/redis
        volumes:
            - redis:/data
        ports:
            - "6380:6379"

    supervisord:
        container_name: "railt_org_supervisor"
        build: ./docker/supervisord
        volumes:
            - "./docker/.mount/supervisor/:/var/log/supervisor"
        volumes_from:
            - php
        depends_on:
            - php

volumes:
    mysql:
        driver: "local"
    sentry:
        driver: "local"
    redis:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
