imports:
  - { resource: services/*.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  #
  # --------------------------------------------------------------------------
  #   Controllers
  # --------------------------------------------------------------------------
  #
  # Controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class.
  #
  App\Application\Controller\:
    resource: '%kernel.project_dir%/app/Application/Controller/'
    tags: [ 'controller.service_arguments' ]

  #
  # --------------------------------------------------------------------------
  #   Console Commands
  # --------------------------------------------------------------------------
  #

  App\Application\Command\DocsUpdateCommand:
    tags:
      - { name: 'console.command' }

  #
  # --------------------------------------------------------------------------
  #   Services
  # --------------------------------------------------------------------------
  #

  App\Infrastructure\Slug\CaseInsensitiveSlugger: ~
