# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #
    # -----------------------------------------------------------------------------
    #   Database Repositories
    # -----------------------------------------------------------------------------
    #

    App\Domain\MenuRepositoryInterface:
        class: App\Infrastructure\Persistence\Repository\MenuRepository

    App\Domain\DocumentationRepositoryInterface:
        class: App\Infrastructure\Persistence\Repository\DocumentationRepository

    App\Domain\SearchIndexRepositoryInterface:
        class: App\Infrastructure\Persistence\Repository\SearchIndexRepository

    #
    # --------------------------------------------------------------------------
    #   Controllers
    # --------------------------------------------------------------------------
    #
    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class.
    #
    App\Application\Controller\:
        resource: '../app/Application/Controller/'
        tags: ['controller.service_arguments']

    #
    # --------------------------------------------------------------------------
    #   Console Commands
    # --------------------------------------------------------------------------
    #

    App\Application\Command\DocsUpdateCommand:
        autowire: true
        arguments:
            - "%kernel.project_dir%/resources/docs"
        tags:
            - { name: 'console.command' }

    #
    # --------------------------------------------------------------------------
    #   Twig Extensions
    # --------------------------------------------------------------------------
    #

    App\Twig\HighlightExtension\HighlightExtension:
        tags: ['twig.extension']

    #
    # --------------------------------------------------------------------------
    #   Services
    # --------------------------------------------------------------------------
    #

    Highlight\Highlighter:
        calls:
            - registerLanguage: ['ebnf', '%kernel.project_dir%/resources/lang/pp2.json']
            - registerLanguage: ['bnf', '%kernel.project_dir%/resources/lang/pp2.json']
            - registerLanguage: ['pp2', '%kernel.project_dir%/resources/lang/pp2.json']
            - registerLanguage: ['pp', '%kernel.project_dir%/resources/lang/pp2.json']
            - registerLanguage: ['ast', '%kernel.project_dir%/resources/lang/ast.json']
            - registerLanguage: ['graphql', '%kernel.project_dir%/resources/lang/graphql.json']
            - registerLanguage: ['gql', '%kernel.project_dir%/resources/lang/graphql.json']
            - registerLanguage: ['accord', '%kernel.project_dir%/resources/lang/accord.json']

    App\Domain\Sync\MenuUpdater:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $repository: '@App\Domain\MenuRepositoryInterface'

    App\Domain\Sync\DocsUpdater:
        arguments:
            $em: '@doctrine.orm.entity_manager'

    App\Domain\Sync\SearchIndexUpdater:
        arguments:
            $em: '@doctrine.orm.entity_manager'

    League\CommonMark\ConverterInterface:
        class: League\CommonMark\GithubFlavoredMarkdownConverter
        arguments:
          - allow_unsafe_links: true
